### ISSUE TITLE
Internal Server Error on uploading

### ISSUE THREAD

**Issue by causztic** [randName/sutd-timetable#16]
I get these on console:

<img width="650" alt="screenshot 2019-01-21 at 10 20 41 am" src="https://user-images.githubusercontent.com/2081441/51449283-3dab0a80-1d66-11e9-8a34-b82201473153.png">

[My Class Schedule.html.txt](https://github.com/randName/sutd-timetable/files/2777363/My.Class.Schedule.html.txt)

**Comment by junqingchang** [comment]
![image](https://user-images.githubusercontent.com/17493562/51450319-4b16c380-1d6b-11e9-848c-9cb04416e45f.png)
Same issue as well

**Comment by randName** [comment]
is this the old version? (wtf jquery) Please give the [new version](https://opensutd.github.io/sutd-timetable/) a try first because I'm trying to deprecate the old version

**Comment by causztic** [comment]
Oh didn't know there's a new URL cos it's not on the readme haha. (and yeah wtf jquery i thought you moving to serverless would remove that dependency)

**Comment by Yustynn** [comment]
Yeah I didn't know about the new version too. Might wanna post it on sutd family @randName

**Comment by randName** [comment]
@Yustynn that sounds good actually, I was just hesitant because I still can't get a calendar view but other than that it's ok alr
