### ISSUE TITLE
Shows successful upload message but didn't upload actually

### ISSUE THREAD

**Issue by jasonswee** [randName/sutd-timetable#2]
![capture](https://cloud.githubusercontent.com/assets/13789695/18262905/601e658c-7438-11e6-9e43-873ef6d30777.PNG)

Successfully uploaded, it didn't create a new class under freshmore..

From F05

**Comment by Sylphias** [comment]
It's there, search under the module name under SC05
<img width="1143" alt="screenshot 2016-09-06 13 51 58" src="https://cloud.githubusercontent.com/assets/5444382/18263020/35eae9ec-7439-11e6-945d-36c01b6ff9ad.png">

**Comment by jasonswee** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13789695/18263151/4368674c-743a-11e6-8744-b28ac2b42fbe.png)
As in cannot select cohort class? @Sylphias

**Comment by jasonswee** [comment]
Refreshed, and it appeared. Closing issue.
