### ISSUE TITLE
Unable to upload and download modules

### ISSUE THREAD

**Issue by huixiang01** [randName/sutd-timetable#24]
Uploaded the timetable in html to https://opensutd.org/sutd-timetable/#/main

Does not seem to update. Although there is term 3 lessons available to download from open sutd but apparently they are all term 2 lessons...

![Annotation 2020-01-20 210143](https://user-images.githubusercontent.com/45475865/72728381-319b9800-3bc8-11ea-92c8-c73fa21a0493.png)

Can help? 0.o

**Comment by randName** [comment]
the `t=2019-2` url parameter should probably be updated to `t=2020-0`

**Comment by huixiang01** [comment]
Okay I checked. It works. But after choosing courses, it will show 2019-2 instead of 2020-0. You may want to change this small bug.

Regards
Hui Xiang
Class of 2022
SUTD
________________________________

**Comment by randName** [comment]
you may bring the issue over to [OpenSUTD/sutd-timetable](https://github.com/OpenSUTD/sutd-timetable/issues); this repository is no longer maintained
