### ISSUE TITLE
Database got removed?

### ISSUE THREAD

**Issue by jasonswee** [randName/sutd-timetable#5]
![capture](https://cloud.githubusercontent.com/assets/13789695/20248564/b7490fe6-aa21-11e6-86bb-8a7dc26a6f01.png)

**Comment by jasonswee** [comment]
@randName

**Comment by randName** [comment]
Seems like they updated the Redis build and my keys got wiped. I can't remember which sections belong to which class, so if you have a list I can restore at least some groups

**Comment by jasonswee** [comment]
http://sutd-timetable.herokuapp.com/calendar?1004,1010,1019,1025,1035,1040,1048
Do you mean these numbers?

![capture](https://cloud.githubusercontent.com/assets/13789695/20252144/a89a41de-aa5a-11e6-8af3-9c55ac55f8b8.png)

**Comment by randName** [comment]
yes. I will be adding this set

**Comment by jasonswee** [comment]
![capture](https://cloud.githubusercontent.com/assets/13789695/22010332/7bd1741a-dcc3-11e6-8b00-9c046ac0eac9.PNG)

Uploaded timetable successfully but not reflected on the system 
@randName

**Comment by randName** [comment]
@jasonswee added; this one is still manual unforunately

**Comment by jasonswee** [comment]
Yep it is updated already, however the google calendar isn't syncing with url given though @randName 

Edit: It synced! probably takes awhile to load
